---
title: "EID Surveillance Assignment"
author: "Mia Isaacs"
date: "2024-11-18"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

## 2008-2013 data

```{r}
flusurv_df = 
  read_excel('data/flusurv_assignment.xlsx', na = c("99", "")) |> 
  janitor::clean_names() |> 
  rename( 
    study_id = study_id1,
    age = age_g,
    month = month1,
    year = year1,
    ) |> 
  mutate(study_id = str_sub(study_id, 8))

view(flusurv_df)
```

# question 1 

```{r}
question1 <- flusurv_df |> 
  filter(flu_pos == 1) |>
  group_by(year, month) |>
  summarize(
    flu_pos_count = n(),
    .groups = "drop"           
  )

view(question1)
```

# question 2

```{r}
question2 <- flusurv_df |> 
  filter(year == 2012 & month >= 7 | year == 2013 & month <= 6) |> 
  summarize(
    flu_a_count = sum(flu_a, na.rm = TRUE),
    pre_2009_h1n1_count = sum(pre_2009_h1n1, na.rm = TRUE),
    a_h3n2_count = sum(a_h3n2, na.rm = TRUE),
    swinf_count = sum(swinf, na.rm = TRUE),
    h5_count = sum(h5, na.rm = TRUE),
    flu_b_count = sum(flu_b, na.rm = TRUE)
  )

view(question2)
```

# question 3

```{r}
flusurv2014_df =
  read_excel('data/flusurv_assignment.xlsx', sheet = 'New 2014 Data', na = c("99", "")) |> 
  janitor::clean_names() |> 
  rename( 
    study_id = study_id1,
    age = age_g,
    month = month1,
    year = year1,
    ) |> 
  mutate(study_id = str_sub(study_id, 8))

view(flusurv2014_df)
```

```{r}
flu_2014_sum <- flusurv2014_df |> 
  filter(epi_week >= 2 & epi_week <= 15, flu_pos == 1) |> 
  group_by(epi_week) |> 
  summarize(
    flu_pos_count = n(),
    .groups = "drop")

view(flu_2014_sum)
```

# question 4

```{r}
question4 <- flusurv2014_df |> 
  filter(epi_week >= 2 & epi_week <= 15) |>         
  mutate(
    epi_week_group = case_when(
      epi_week >= 2 & epi_week <= 12 ~ "2-12",
      epi_week >= 13 & epi_week <= 15 ~ "13-15"
    )
  ) |> 
  group_by(epi_week_group) |>                       
  summarize(
    
    total_count_age = sum(!is.na(age)),
    age_15_49 = sum(age == 4, na.rm = TRUE),  
    age_proportion = age_15_49 / total_count_age,
    
    total_count_icu = sum(!is.na(icu)),
    icu_count = sum(icu == 1, na.rm = TRUE),
    icu_proportion = icu_count / total_count_icu,
    
    total_count_outcome = sum(!is.na(outcome)),
    outcome_count = sum(outcome == 3, na.rm = TRUE),
    outcome_proportion = outcome_count / total_count_outcome,
    
    .groups = "drop"
  )

view(question4)
```







